"use client";
import { use, useEffect, useState } from "react";
import Link from "next/link";
import { CalendarDays, Download, ExternalLink, FileText, Image as ImageIcon, Link2, LockKeyhole, Video } from "lucide-react";
import { useLang } from "@/lib/language-context";
import MandalaLoader from "@/components/MandalaLoader";
import type { WorkshopDay, WorkshopMaterial } from "@/lib/workshops";
type W={id:string;title:string;description:string|null;start_date:string|null;end_date:string|null;schedule:WorkshopDay[];notes:string|null;materials:WorkshopMaterial[]};
const txt={ar:{back:"العودة لمسار الورش",program:"البرنامج الزمني",training:"تدريب",rest:"إجازة / راحة",materials:"محتوى الورشة",notes:"ملاحظات المدرب",locked:"المحتوى محفوظ للحاضرين",lockedSub:"سجّل حضورك في الورشة أولاً، وبعدها ستظهر لك الشرائح والصور والروابط والملاحظات هنا.",empty:"لم يضف المشرف محتوى لهذه الورشة بعد.",open:"فتح المحتوى",download:"تنزيل"},sq:{back:"Kthehu te punëtoritë",program:"Programi",training:"Trajnim",rest:"Pushim",materials:"Materialet",notes:"Shënimet",locked:"Materialet janë për pjesëmarrësit",lockedSub:"Regjistro praninë dhe materialet do të shfaqen këtu.",empty:"Nuk ka materiale ende.",open:"Hap",download:"Shkarko"}} as const;
export default function TeacherWorkshopDetail({params}:{params:Promise<{id:string}>}){const{id}=use(params);const{lang}=useLang();const L=lang==="sq"?"sq":"ar",T=txt[L];const[data,setData]=useState<{workshop:W;attended:boolean}|null>(null),[loading,setLoading]=useState(true);useEffect(()=>{fetch(`/api/teacher/workshops/${id}`,{cache:"no-store"}).then(r=>r.json()).then(setData).finally(()=>setLoading(false))},[id]);const fmt=(d:string)=>new Date(d).toLocaleDateString(L==="ar"?"ar-SA-u-ca-gregory-nu-latn":"sq-AL",{weekday:"short",day:"numeric",month:"long",year:"numeric",timeZone:"UTC"});if(loading)return <MandalaLoader/>;if(!data?.workshop)return null;const w=data.workshop;return <div className="td" dir={L==="ar"?"rtl":"ltr"}><Link className="back" href="/teacher/workshops">{T.back}</Link><header><div><CalendarDays size={20}/><span>{w.start_date?fmt(w.start_date):"-"}</span></div><h1>{w.title}</h1>{w.description&&<p>{w.description}</p>}</header><section><h2>{T.program}</h2><div className="days">{w.schedule.map((d,i)=><div className={d.type.toLowerCase()} key={d.date}><b>{i+1}</b><span>{fmt(d.date)}</span><strong>{d.type==="WORK"?T.training:T.rest}</strong>{d.type==="WORK"&&<small>{d.start_time} - {d.end_time}</small>}</div>)}</div></section><section><h2>{T.materials}</h2>{!data.attended?<div className="locked"><LockKeyhole size={28}/><b>{T.locked}</b><p>{T.lockedSub}</p></div>:w.materials.length===0?<div className="empty">{T.empty}</div>:<div className="materials">{w.materials.map(m=><article key={m.id}>{m.type==="IMAGE"?<ImageIcon/>:m.type==="VIDEO"?<Video/>:m.type==="LINK"?<Link2/>:<FileText/>}<div><b>{m.title}</b><small>{m.mime||m.type}</small></div><a href={m.url} target="_blank" rel="noreferrer">{m.type==="FILE"?<Download size={17}/>:<ExternalLink size={17}/>}<span>{m.type==="FILE"?T.download:T.open}</span></a></article>)}</div>}{data.attended&&w.notes&&<div className="notes"><b>{T.notes}</b><p>{w.notes}</p></div>}</section><style>{css}</style></div>}
const css=`.td{font-family:'Cairo',sans-serif;color:#32101A;max-width:1100px;margin:auto}.back{display:inline-block;color:#6B1E2D;font-weight:900;text-decoration:none;font-size:12px;margin-bottom:12px}.td header{background:#1A1A1A;color:#F7F3EB;padding:26px;border-radius:8px;margin-bottom:14px}.td header>div{display:flex;align-items:center;gap:7px;color:#D9C9B0;font-size:12px}.td h1{font-size:30px;margin:10px 0 5px}.td header p{color:#D9C9B0;max-width:800px;margin:0}.td section{background:#FFFBF5;border:1px solid #D9C9B0;padding:18px;margin-bottom:14px;border-radius:8px}.td section h2{font-size:18px;margin:0 0 12px}.days{display:flex;overflow:auto}.days>div{min-width:160px;padding:12px;background:#EFEAE0;border-top:3px solid #1B5E20}.days>div.rest{border-color:#8C8274;background:#EFEAE0}.days b,.days span,.days strong,.days small{display:block}.days b{width:24px;height:24px;border-radius:50%;display:grid;place-items:center;background:#32101A;color:#D9C9B0;font-size:11px}.days span,.days small{font-size:11px;color:#655B53;margin-top:5px}.days strong{font-size:12px;margin-top:4px}.locked,.empty{text-align:center;padding:45px;background:#F7F3EB;color:#796A62}.locked svg{color:#6B1E2D}.locked b{display:block;margin-top:8px}.locked p{font-size:12px;margin:4px auto 0;max-width:500px}.materials{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:8px}.materials article{display:grid;grid-template-columns:30px 1fr auto;align-items:center;gap:9px;border:1px solid #E5E0D5;background:#fff;padding:12px}.materials article>svg{color:#6B1E2D}.materials b,.materials small{display:block}.materials b{font-size:12px}.materials small{font-size:10px;color:#796A62}.materials a{display:flex;align-items:center;gap:5px;color:#6B1E2D;font-size:11px;font-weight:900;text-decoration:none}.notes{margin-top:14px;padding:14px;border-inline-start:3px solid #6B1E2D;background:#F7F3EB}.notes p{white-space:pre-wrap;margin:5px 0 0;font-size:13px}@media(max-width:600px){.td h1{font-size:24px}.td header{padding:20px}.materials{grid-template-columns:1fr}.materials a span{display:none}}`;
