"use client";
export const dynamic = "force-dynamic";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState, type CSSProperties, type ReactNode } from "react";
import {
  Activity, Ban, BookOpenCheck, CheckCircle2, ChevronDown, CircleUserRound,
  Download, Layers3, MapPin, Radar, Search, SlidersHorizontal, Target, Users, X,
} from "lucide-react";
import { useLang } from "@/lib/language-context";
import { useConfirm } from "@/lib/confirm-dialog";
import MandalaLoader from "@/components/MandalaLoader";
import IdentityMandala from "@/components/IdentityMandala";
import IdentityStar from "@/components/IdentityStar";

type Lang = "ar" | "sq" | "en";
type JourneyFilter = "" | "started" | "not_started" | "completed";
interface StageProgress { title: string; passed: number; total: number }
interface RecentAttempt { module_title: string; stage_title: string; score_pct: number; passed: boolean; date: string }
interface Student {
  id: string; onboarding_status: string; created_at: string; city: string | null; age: number | null;
  profile: { full_name: string; email: string | null; avatar_url: string | null; is_active: boolean };
  class: { id: string; name: string } | null;
  attempts_count: number; passed_count: number; total_modules: number; avg_score: number | null; progress_pct: number;
  current_stage: { id: string; title: string; order: number } | null;
  current_module: { id: string; title: string } | null;
  stage_progress: StageProgress[]; recent_attempts: RecentAttempt[];
}
interface ClassItem { id: string; name: string }

const COPY = {
  ar: {
    eyebrow: "إدارة رحلة المستفيدين", title: "المستفيدون", subtitle: "ملف واضح لكل مستفيد: موقعه في الرحلة، تقدمه، مجموعته وآخر محاولاته.", beneficiaries: "مستفيد", activeAccounts: "حساب نشط", assigned: "داخل مجموعة", started: "بدأوا الرحلة",
    search: "ابحث بالاسم، البريد، المجموعة، المرحلة أو المفهوم...", export: "تصدير المستفيدين Excel", exporting: "جارٍ التصدير...", classes: "إدارة المجموعات", filters: "تصفية النتائج", results: "نتيجة", clear: "مسح التصفية",
    class: "المجموعة", allClasses: "كل المجموعات", unassigned: "بدون مجموعة", journey: "حالة الرحلة", allJourneys: "كل الحالات", inProgress: "قيد التقدم", notStarted: "لم يبدأ", completed: "أكمل الرحلة", account: "حالة الحساب", allAccounts: "كل الحسابات", active: "نشط", inactive: "معطّل",
    noResults: "لا يوجد مستفيدون مطابقون للتصفية الحالية.", openProfile: "فتح الملف الشامل", showDetails: "عرض التقدم السريع", hideDetails: "إخفاء التفاصيل", currentPosition: "الموقع الحالي", noPosition: "لم يبدأ رحلة التعلم بعد", attempts: "محاولات", concepts: "مفاهيم مكتملة", average: "متوسط الأداء", stageProgress: "تقدم المراحل", recentAttempts: "آخر المحاولات",
    assignClass: "تعيين المجموعة", noClass: "بدون مجموعة", deactivate: "تعطيل المستفيد", activate: "تفعيل المستفيد", loading: "جارٍ تحميل المستفيدين...", loadError: "تعذر تحميل المستفيدين.", toggleError: "تعذر تحديث البيانات.", noActivity: "لا توجد محاولات مسجلة بعد.", joined: "انضم",
  },
  sq: {
    eyebrow: "Menaxhimi i rrugëtimit", title: "Pjesëmarrësit", subtitle: "Pamje e qartë për çdo pjesëmarrës: pozicioni, përparimi, grupi dhe përpjekjet e fundit.", beneficiaries: "pjesëmarrës", activeAccounts: "llogari aktive", assigned: "në grup", started: "kanë filluar",
    search: "Kërko sipas emrit, emailit, grupit, fazës ose konceptit...", export: "Eksporto pjesëmarrësit në Excel", exporting: "Duke eksportuar...", classes: "Menaxho grupet", filters: "Filtrimi", results: "rezultate", clear: "Pastro filtrat",
    class: "Grupi", allClasses: "Të gjitha grupet", unassigned: "Pa grup", journey: "Gjendja e rrugëtimit", allJourneys: "Të gjitha gjendjet", inProgress: "Në vazhdim", notStarted: "Pa filluar", completed: "Rrugëtimi i përfunduar", account: "Gjendja e llogarisë", allAccounts: "Të gjitha llogaritë", active: "Aktive", inactive: "Jo aktive",
    noResults: "Asnjë pjesëmarrës nuk përputhet me filtrat.", openProfile: "Hap profilin e plotë", showDetails: "Shfaq përparimin", hideDetails: "Fshih detajet", currentPosition: "Pozicioni aktual", noPosition: "Ende nuk e ka filluar rrugëtimin", attempts: "Përpjekje", concepts: "Koncepte të përfunduara", average: "Mesatarja", stageProgress: "Përparimi sipas fazave", recentAttempts: "Përpjekjet e fundit",
    assignClass: "Cakto grupin", noClass: "Pa grup", deactivate: "Çaktivizo pjesëmarrësin", activate: "Aktivizo pjesëmarrësin", loading: "Duke ngarkuar pjesëmarrësit...", loadError: "Pjesëmarrësit nuk u ngarkuan.", toggleError: "Të dhënat nuk u përditësuan.", noActivity: "Ende nuk ka përpjekje.", joined: "Regjistruar",
  },
  en: {
    eyebrow: "Beneficiary journey management", title: "Beneficiaries", subtitle: "A clear profile for every beneficiary: journey position, progress, group and recent attempts.", beneficiaries: "beneficiaries", activeAccounts: "active accounts", assigned: "assigned", started: "started journey",
    search: "Search by name, email, group, stage or concept...", export: "Export beneficiaries to Excel", exporting: "Exporting...", classes: "Manage groups", filters: "Filters", results: "results", clear: "Clear filters",
    class: "Group", allClasses: "All groups", unassigned: "Unassigned", journey: "Journey status", allJourneys: "All journey states", inProgress: "In progress", notStarted: "Not started", completed: "Journey completed", account: "Account status", allAccounts: "All accounts", active: "Active", inactive: "Inactive",
    noResults: "No beneficiaries match the current filters.", openProfile: "Open complete profile", showDetails: "Show quick progress", hideDetails: "Hide details", currentPosition: "Current position", noPosition: "Learning journey not started yet", attempts: "Attempts", concepts: "Concepts completed", average: "Average score", stageProgress: "Stage progress", recentAttempts: "Recent attempts",
    assignClass: "Assign group", noClass: "No group", deactivate: "Deactivate beneficiary", activate: "Activate beneficiary", loading: "Loading beneficiaries...", loadError: "Beneficiaries could not be loaded.", toggleError: "Data could not be updated.", noActivity: "No attempts recorded yet.", joined: "Joined",
  },
} as const;

function initials(name: string) { return name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase(); }
function date(value: string, lang: Lang) { return new Intl.DateTimeFormat(lang === "ar" ? "ar-SA-u-nu-latn" : lang === "sq" ? "sq-AL" : "en-GB", { dateStyle: "medium" }).format(new Date(value)); }
function journeyOf(student: Student): JourneyFilter { return student.total_modules > 0 && student.passed_count >= student.total_modules ? "completed" : student.attempts_count > 0 ? "started" : "not_started"; }
function statusLabel(status: string, lang: Lang) {
  const labels: Record<string, [string, string, string]> = { PENDING_INTAKE: ["في انتظار القبول", "Në pritje të pranimit", "Pending intake"], INTAKE_SUBMITTED: ["بانتظار المراجعة", "Në pritje të shqyrtimit", "Awaiting review"], SCHOOL_ASSIGNED: ["تم تعيين المنصة", "Platforma e caktuar", "Platform assigned"], SCHOOL_PLACEMENT_SUBMITTED: ["اختبار التصنيف", "Vlerësimi i dorëzuar", "Placement submitted"], CLASS_ASSIGNED: ["في المجموعة", "Në grup", "In group"] };
  const value = labels[status] ?? [status, status, status]; return value[lang === "ar" ? 0 : lang === "sq" ? 1 : 2];
}
function Metric({ icon, value, label }: { icon: ReactNode; value: number | string; label: string }) { return <div className="sd-metric"><span>{icon}</span><div><strong>{value}</strong><small>{label}</small></div></div>; }
function ProgressRing({ value }: { value: number }) { return <div className="sd-ring" style={{ "--progress": `${Math.max(0, Math.min(100, value)) * 3.6}deg` } as CSSProperties}><span>{value}%</span></div>; }

function StudentCard({ student, classes, lang, onAssign, onToggle, toggling }: { student: Student; classes: ClassItem[]; lang: Lang; onAssign: (id: string, classId: string) => void; onToggle: (id: string, active: boolean) => void; toggling: boolean }) {
  const T = COPY[lang]; const [expanded, setExpanded] = useState(false); const journey = journeyOf(student); const journeyLabel = journey === "completed" ? T.completed : journey === "started" ? T.inProgress : T.notStarted;
  return <article className={`sd-card ${student.profile.is_active ? "" : "is-inactive"}`}>
    <div className="sd-watermark" aria-hidden="true"><IdentityMandala size={160} stroke="#4A0E1C" opacity={0.045} /></div>
    <header className="sd-card-head">
      <div className="sd-avatar">{student.profile.avatar_url ? <Image src={student.profile.avatar_url} alt={student.profile.full_name} fill sizes="58px" /> : <span>{initials(student.profile.full_name)}</span>}</div>
      <div className="sd-identity"><div className="sd-name-row"><h2>{student.profile.full_name}</h2><span className={`sd-pill ${journey}`}>{journeyLabel}</span>{!student.profile.is_active && <span className="sd-pill inactive">{T.inactive}</span>}</div><div className="sd-contact">{student.profile.email && <span><CircleUserRound size={12} />{student.profile.email}</span>}<span><Layers3 size={12} />{student.class?.name ?? T.noClass}</span>{student.city && <span><MapPin size={12} />{student.city}</span>}</div></div>
      <button data-write="true" className={`sd-toggle ${student.profile.is_active ? "off" : "on"}`} onClick={() => onToggle(student.id, student.profile.is_active)} disabled={toggling} title={student.profile.is_active ? T.deactivate : T.activate} aria-label={student.profile.is_active ? T.deactivate : T.activate}>{toggling ? "…" : student.profile.is_active ? <Ban size={14} /> : <CheckCircle2 size={14} />}</button>
    </header>
    <div className="sd-card-summary"><div className="sd-position"><span><Target size={15} /></span><div><small>{T.currentPosition}</small><strong>{student.current_stage ? `${student.current_stage.title} · ${student.current_module?.title ?? "—"}` : T.noPosition}</strong></div></div><ProgressRing value={student.progress_pct} /></div>
    <div className="sd-card-metrics"><span><b>{student.attempts_count}</b>{T.attempts}</span><span><b>{student.passed_count}/{student.total_modules}</b>{T.concepts}</span><span><b>{student.avg_score === null ? "—" : `${student.avg_score}%`}</b>{T.average}</span></div>
    <div className="sd-card-actions"><Link href={`/school-admin/students/${student.id}`}>{T.openProfile}</Link><button type="button" onClick={() => setExpanded((value) => !value)} aria-expanded={expanded}>{expanded ? T.hideDetails : T.showDetails}<ChevronDown size={14} className={expanded ? "rotated" : ""} /></button></div>
    {expanded && <div className="sd-expanded">
      <section><h3><Activity size={14} />{T.stageProgress}</h3>{student.stage_progress.length ? <div className="sd-stages">{student.stage_progress.map((stage) => { const pct = stage.total ? Math.round(stage.passed / stage.total * 100) : 0; return <div key={stage.title}><div><strong>{stage.title}</strong><span>{stage.passed}/{stage.total}</span></div><i><b style={{ width: `${pct}%` }} /></i></div>; })}</div> : <p className="sd-muted">{T.noActivity}</p>}</section>
      <section><h3><BookOpenCheck size={14} />{T.recentAttempts}</h3>{student.recent_attempts.length ? <div className="sd-attempts">{student.recent_attempts.slice(0, 3).map((attempt) => <article key={`${attempt.module_title}-${attempt.date}`}><span className={attempt.passed ? "passed" : ""} /><div><strong>{attempt.module_title}</strong><small>{attempt.stage_title} · {date(attempt.date, lang)}</small></div><b>{attempt.score_pct}%</b></article>)}</div> : <p className="sd-muted">{T.noActivity}</p>}</section>
      <label className="sd-assign"><span>{T.assignClass}</span><select data-write="true" value={student.class?.id ?? ""} onChange={(event) => onAssign(student.id, event.target.value)}><option value="">{T.noClass}</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
    </div>}
  </article>;
}

export default function SchoolAdminStudentsPage() {
  const { lang: rawLang } = useLang(); const lang = (rawLang === "sq" ? "sq" : rawLang === "en" ? "en" : "ar") as Lang; const T = COPY[lang]; const dir = lang === "ar" ? "rtl" : "ltr"; const confirm = useConfirm();
  const [students, setStudents] = useState<Student[]>([]); const [classes, setClasses] = useState<ClassItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [classFilter, setClassFilter] = useState(""); const [journeyFilter, setJourneyFilter] = useState<JourneyFilter>(""); const [accountFilter, setAccountFilter] = useState(""); const [toggling, setToggling] = useState<string | null>(null); const [exporting, setExporting] = useState(false);
  useEffect(() => { let active = true; Promise.all([fetch("/api/school-admin/students", { cache: "no-store" }), fetch("/api/school-admin/classes", { cache: "no-store" })]).then(async ([studentResponse, classResponse]) => { if (!studentResponse.ok || !classResponse.ok) throw new Error(); const [studentData, classData] = await Promise.all([studentResponse.json(), classResponse.json()]); if (active) { setStudents(studentData.students ?? []); setClasses(classData.classes ?? []); } }).catch(() => { if (active) setError(T.loadError); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [T.loadError]);
  const visible = useMemo(() => { const needle = query.trim().toLowerCase(); return students.filter((student) => { if (classFilter === "unassigned" && student.class) return false; if (classFilter && classFilter !== "unassigned" && student.class?.id !== classFilter) return false; if (journeyFilter && journeyOf(student) !== journeyFilter) return false; if (accountFilter === "active" && !student.profile.is_active) return false; if (accountFilter === "inactive" && student.profile.is_active) return false; return !needle || [student.profile.full_name, student.profile.email, student.class?.name, student.city, student.current_stage?.title, student.current_module?.title].filter(Boolean).join(" ").toLowerCase().includes(needle); }); }, [accountFilter, classFilter, journeyFilter, query, students]);
  const totals = useMemo(() => ({ active: students.filter((item) => item.profile.is_active).length, assigned: students.filter((item) => item.class).length, started: students.filter((item) => item.attempts_count > 0).length }), [students]); const hasFilters = Boolean(query.trim() || classFilter || journeyFilter || accountFilter); const resetFilters = () => { setQuery(""); setClassFilter(""); setJourneyFilter(""); setAccountFilter(""); };
  async function toggleStudent(id: string, active: boolean) { if (active) { const ok = await confirm({ title: T.deactivate, message: T.deactivate, confirmText: T.deactivate, variant: "warning", irreversible: false }); if (!ok) return; } setToggling(id); setError(""); try { const response = await fetch(`/api/school-admin/students/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ is_active: !active }) }); if (!response.ok) throw new Error(); setStudents((items) => items.map((item) => item.id === id ? { ...item, profile: { ...item.profile, is_active: !active } } : item)); } catch { setError(T.toggleError); } finally { setToggling(null); } }
  async function assignClass(id: string, classId: string) { setError(""); try { const response = await fetch(`/api/school-admin/students/${id}/assign-class`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ class_id: classId || null }) }); if (!response.ok) throw new Error(); const selected = classes.find((item) => item.id === classId) ?? null; setStudents((items) => items.map((item) => item.id === id ? { ...item, class: selected } : item)); } catch { setError(T.toggleError); } }
  async function exportExcel() { setExporting(true); try { const XLSX = await import("xlsx"); const rows = students.map((student) => ({ Name: student.profile.full_name, Email: student.profile.email ?? "", Group: student.class?.name ?? "", Status: statusLabel(student.onboarding_status, lang), Progress: `${student.progress_pct}%`, Attempts: student.attempts_count, Completed: student.passed_count, Average: student.avg_score ?? "", Joined: date(student.created_at, lang) })); const sheet = XLSX.utils.json_to_sheet(rows); sheet["!cols"] = [{ wch: 28 }, { wch: 30 }, { wch: 24 }, { wch: 22 }, { wch: 12 }, { wch: 12 }, { wch: 12 }, { wch: 12 }, { wch: 18 }]; const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, sheet, "Beneficiaries"); XLSX.writeFile(workbook, `beneficiaries-${new Date().toISOString().slice(0, 10)}.xlsx`); } finally { setExporting(false); } }
  if (loading) return <MandalaLoader label={T.loading} />;
  return <main className="sd-page" dir={dir}>
    <section className="sd-hero"><div className="sd-hero-art" aria-hidden="true"><IdentityMandala size={290} stroke="#D9C9B0" opacity={0.12} spin spinDuration={140} /></div><div><p className="sd-eyebrow"><IdentityStar size={11} strokeWidth={5} color="#D9C9B0" />{T.eyebrow}</p><h1>{T.title}</h1><p>{T.subtitle}</p></div><div className="sd-hero-metrics"><Metric icon={<Users />} value={students.length} label={T.beneficiaries} /><Metric icon={<CheckCircle2 />} value={totals.active} label={T.activeAccounts} /><Metric icon={<Layers3 />} value={totals.assigned} label={T.assigned} /><Metric icon={<Activity />} value={totals.started} label={T.started} /></div></section>
    <section className="sd-toolbar"><label><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={T.search} /></label><button onClick={() => void exportExcel()} disabled={exporting}><Download size={15} />{exporting ? T.exporting : T.export}</button><Link href="/school-admin/classes"><Layers3 size={15} />{T.classes}</Link></section>
    <section className="sd-filters"><header><SlidersHorizontal size={15} /><span>{T.filters}</span><em>{visible.length} {T.results}</em>{hasFilters && <button onClick={resetFilters}><X size={13} />{T.clear}</button>}</header><div><label><span>{T.class}</span><select value={classFilter} onChange={(event) => setClassFilter(event.target.value)}><option value="">{T.allClasses}</option><option value="unassigned">{T.unassigned}</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>{T.journey}</span><select value={journeyFilter} onChange={(event) => setJourneyFilter(event.target.value as JourneyFilter)}><option value="">{T.allJourneys}</option><option value="started">{T.inProgress}</option><option value="not_started">{T.notStarted}</option><option value="completed">{T.completed}</option></select></label><label><span>{T.account}</span><select value={accountFilter} onChange={(event) => setAccountFilter(event.target.value)}><option value="">{T.allAccounts}</option><option value="active">{T.active}</option><option value="inactive">{T.inactive}</option></select></label></div></section>
    {error && <div className="sd-error">{error}</div>}
    {visible.length ? <section className="sd-grid">{visible.map((student) => <StudentCard key={student.id} student={student} classes={classes} lang={lang} onAssign={assignClass} onToggle={toggleStudent} toggling={toggling === student.id} />)}</section> : <section className="sd-empty"><Radar size={30} /><p>{T.noResults}</p>{hasFilters && <button onClick={resetFilters}>{T.clear}</button>}</section>}
    <style>{styles}</style>
  </main>;
}

const styles = `
@import url('https://fonts.googleapis.com/css2?family=Noto+Kufi+Arabic:wght@500;700&family=Cairo:wght@400;600;700;800&display=swap');@keyframes sd-in{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:none}}
.sd-page{--head:'Noto Kufi Arabic','Cairo',sans-serif;display:flex;flex-direction:column;gap:18px;color:#1A1A1A;font-family:'Cairo',sans-serif}.sd-hero{position:relative;isolation:isolate;overflow:hidden;display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:end;gap:24px;padding:29px 31px;border:1px solid rgba(184,160,130,.36);border-radius:26px;background:radial-gradient(circle at 8% 120%,rgba(107,30,45,.58),transparent 44%),linear-gradient(140deg,#32101A,#4A0E1C 58%,#5B1526);color:#FFFBF5;box-shadow:0 24px 56px rgba(50,16,26,.24)}.sd-hero:before{content:"";position:absolute;top:0;inset-inline:28px;height:2px;background:linear-gradient(90deg,transparent,#D9C9B0,transparent);opacity:.55}.sd-hero-art{position:absolute;inset-inline-end:-68px;top:50%;z-index:-1;transform:translateY(-50%)}.sd-eyebrow{display:flex!important;align-items:center;gap:8px!important;margin:0 0 6px!important;color:#D9C9B0!important;font-size:10.5px!important;font-weight:800!important;letter-spacing:.15em}.sd-hero h1{margin:0;font-family:var(--head);font-size:29px;line-height:1.4}.sd-hero>div>p:last-child{max-width:630px;margin:7px 0 0;color:rgba(255,251,245,.7);font-size:13px;line-height:1.85}.sd-hero-metrics{position:relative;z-index:1;display:grid;grid-template-columns:repeat(4,minmax(82px,1fr));gap:9px}.sd-metric{display:flex;align-items:center;gap:10px;min-width:0;padding:12px;border:1px solid rgba(107,30,45,.11);border-radius:16px;background:#FFFBF5}.sd-metric>span{width:34px;height:34px;flex:none;display:grid;place-items:center;border-radius:11px;background:#F7F3EB;color:#6B1E2D}.sd-metric svg{width:16px}.sd-metric div{min-width:0}.sd-metric strong{display:block;font-size:20px;line-height:1}.sd-metric small{display:block;margin-top:5px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#796A62;font-size:9px;font-weight:800}.sd-hero .sd-metric{min-height:78px;background:rgba(26,10,16,.34);border-color:rgba(217,201,176,.24)}.sd-hero .sd-metric>span{background:rgba(255,251,245,.08);color:#D9C9B0}.sd-hero .sd-metric strong{color:#D9C9B0}.sd-hero .sd-metric small{color:rgba(255,251,245,.62)}
.sd-toolbar{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.sd-toolbar>label{flex:1;min-width:280px;height:48px;display:flex;align-items:center;gap:9px;padding:0 15px;border:1px solid rgba(184,160,130,.24);border-radius:16px;background:#FFFBF5;color:#8F765B}.sd-toolbar input{width:100%;height:100%;border:0;outline:0;background:transparent;color:#1A1A1A;font:700 12.5px 'Cairo',sans-serif}.sd-toolbar button,.sd-toolbar a{height:48px;display:inline-flex;align-items:center;justify-content:center;gap:7px;padding:0 17px;border:1px solid rgba(184,160,130,.34);border-radius:16px;background:linear-gradient(180deg,#5B1526,#32101A);color:#D9C9B0;font:700 11.5px 'Cairo',sans-serif;text-decoration:none;cursor:pointer;transition:.18s}.sd-toolbar button:hover,.sd-toolbar a:hover{transform:translateY(-1px);box-shadow:0 8px 20px rgba(50,16,26,.18)}.sd-toolbar button:disabled{opacity:.55}
.sd-filters{position:relative;overflow:hidden;padding:16px 18px;border:1px solid rgba(184,160,130,.24);border-radius:20px;background:linear-gradient(180deg,#FFFBF5,#F7F3EB);box-shadow:0 10px 26px rgba(50,16,26,.045)}.sd-filters:before{content:"";position:absolute;top:0;inset-inline:18px;height:2px;background:linear-gradient(90deg,transparent,#B8A082,transparent)}.sd-filters>header{display:flex;align-items:center;gap:8px;margin-bottom:13px;color:#655B53}.sd-filters>header svg{color:#B8A082}.sd-filters>header>span{font-family:var(--head);font-size:12px;font-weight:700}.sd-filters>header em{padding:2px 9px;border:1px solid rgba(184,160,130,.24);border-radius:999px;background:rgba(184,160,130,.13);color:#6B1E2D;font-size:10px;font-style:normal;font-weight:800}.sd-filters>header button{margin-inline-start:auto;display:flex;align-items:center;gap:5px;padding:4px 11px;border:1px solid rgba(107,30,45,.2);border-radius:999px;background:transparent;color:#6B1E2D;font:700 10px 'Cairo',sans-serif;cursor:pointer}.sd-filters>div{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.sd-filters label{display:grid;gap:6px}.sd-filters label>span{color:#8F765B;font-size:10px;font-weight:800}.sd-filters select{height:42px;padding:0 12px;border:1px solid rgba(184,160,130,.28);border-radius:13px;background:#FFF;color:#1A1A1A;outline:0;font:700 12px 'Cairo',sans-serif}.sd-error{padding:11px 14px;border:1px solid rgba(107,30,45,.2);border-radius:13px;background:rgba(107,30,45,.07);color:#6B1E2D;font-size:12px;font-weight:800}
.sd-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;align-items:start}.sd-card{position:relative;overflow:hidden;display:flex;flex-direction:column;gap:12px;padding:17px 18px;border:1px solid rgba(184,160,130,.24);border-radius:24px;background:linear-gradient(180deg,#FFFBF5,#FBF8F1 70%,#F7F3EB);box-shadow:0 14px 34px rgba(50,16,26,.06),inset 0 1px rgba(255,255,255,.8);animation:sd-in .35s ease both;transition:.2s}.sd-card:hover{transform:translateY(-3px);border-color:rgba(184,160,130,.48);box-shadow:0 22px 46px rgba(50,16,26,.11)}.sd-card:before{content:"";position:absolute;top:0;inset-inline:22px;height:2px;background:linear-gradient(90deg,transparent,#B8A082,transparent)}.sd-card.is-inactive{filter:saturate(.72)}.sd-watermark{position:absolute;inset-inline-end:-35px;bottom:-40px;pointer-events:none}.sd-card-head{position:relative;z-index:1;display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:13px;align-items:start}.sd-avatar{position:relative;width:58px;height:58px;overflow:hidden;display:grid;place-items:center;border:1px solid rgba(184,160,130,.34);border-radius:17px;background:linear-gradient(145deg,#4A0E1C,#1A1A1A);color:#D9C9B0;font-family:var(--head);font-size:16px;font-weight:700;box-shadow:0 8px 18px rgba(50,16,26,.16)}.sd-avatar img{object-fit:cover}.sd-identity{min-width:0}.sd-name-row{display:flex;align-items:center;gap:7px;flex-wrap:wrap}.sd-name-row h2{margin:0;font-family:var(--head);font-size:16px;line-height:1.5}.sd-pill{padding:3px 8px;border:1px solid rgba(184,160,130,.2);border-radius:999px;background:rgba(184,160,130,.11);color:#8F765B;font-size:9px;font-weight:900}.sd-pill.completed{background:rgba(27,94,32,.08);border-color:rgba(27,94,32,.18);color:#1B5E20}.sd-pill.inactive{background:rgba(107,30,45,.07);border-color:rgba(107,30,45,.18);color:#6B1E2D}.sd-contact{display:flex;gap:10px;flex-wrap:wrap;margin-top:7px}.sd-contact span{display:inline-flex;align-items:center;gap:5px;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#796A62;font-size:10.5px;font-weight:700}.sd-contact svg{flex:none;color:#B8A082}.sd-toggle{width:30px;height:30px;display:grid;place-items:center;border-radius:9px;cursor:pointer}.sd-toggle.off{border:1px solid rgba(107,30,45,.18);background:rgba(107,30,45,.05);color:#6B1E2D}.sd-toggle.on{border:1px solid rgba(27,94,32,.2);background:rgba(27,94,32,.07);color:#1B5E20}.sd-toggle:disabled{opacity:.45}
.sd-card-summary{position:relative;z-index:1;display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:12px;padding:12px;border:1px solid rgba(184,160,130,.15);border-radius:17px;background:rgba(255,255,255,.58)}.sd-position{display:flex;align-items:center;gap:10px;min-width:0}.sd-position>span{width:36px;height:36px;flex:none;display:grid;place-items:center;border-radius:11px;background:#F7F3EB;color:#6B1E2D}.sd-position small,.sd-position strong{display:block}.sd-position small{color:#8F765B;font-size:8.5px;font-weight:900}.sd-position strong{margin-top:3px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#32101A;font-size:10.5px}.sd-ring{--progress:0deg;width:57px;height:57px;display:grid;place-items:center;flex:none;border-radius:50%;background:conic-gradient(#8F765B var(--progress),#E5E0D5 0);position:relative}.sd-ring:after{content:"";position:absolute;inset:6px;border-radius:50%;background:#FFFBF5}.sd-ring span{position:relative;z-index:1;color:#6B1E2D;font-size:10px;font-weight:900}.sd-card-metrics{position:relative;z-index:1;display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.sd-card-metrics span{display:flex;flex-direction:column;padding:8px 9px;border-radius:12px;background:rgba(184,160,130,.08);color:#796A62;font-size:8.5px;font-weight:800}.sd-card-metrics b{color:#32101A;font-size:13px}.sd-card-actions{position:relative;z-index:1;display:grid;grid-template-columns:1fr 1fr;gap:8px}.sd-card-actions a,.sd-card-actions button{min-height:38px;display:flex;align-items:center;justify-content:center;gap:6px;border-radius:11px;font:800 10px 'Cairo',sans-serif;text-decoration:none;cursor:pointer}.sd-card-actions a{border:1px solid rgba(184,160,130,.34);background:linear-gradient(180deg,#5B1526,#32101A);color:#F7F3EB}.sd-card-actions button{border:1px solid rgba(107,30,45,.15);background:#F7F3EB;color:#6B1E2D}.sd-card-actions svg{transition:.18s}.sd-card-actions svg.rotated{transform:rotate(180deg)}
.sd-expanded{position:relative;z-index:1;display:grid;grid-template-columns:1fr 1fr;gap:12px;padding-top:13px;border-top:1px dashed rgba(184,160,130,.25);animation:sd-in .22s ease}.sd-expanded>section{padding:12px;border:1px solid rgba(184,160,130,.15);border-radius:15px;background:rgba(255,255,255,.55)}.sd-expanded h3{display:flex;align-items:center;gap:6px;margin:0 0 10px;color:#655B53;font-size:10.5px}.sd-expanded h3 svg{color:#8F765B}.sd-stages{display:grid;gap:8px}.sd-stages>div>div{display:flex;justify-content:space-between;gap:8px}.sd-stages strong{font-size:9.5px}.sd-stages span{color:#8F765B;font-size:8.5px}.sd-stages i{height:5px;display:block;overflow:hidden;margin-top:4px;border-radius:999px;background:#E5E0D5}.sd-stages b{display:block;height:100%;border-radius:inherit;background:linear-gradient(90deg,#6B1E2D,#B8A082)}.sd-attempts{display:grid;gap:6px}.sd-attempts article{display:grid;grid-template-columns:7px minmax(0,1fr) auto;align-items:center;gap:7px}.sd-attempts article>span{width:7px;height:7px;border-radius:50%;background:#B8A082}.sd-attempts article>span.passed{background:#1B5E20}.sd-attempts strong,.sd-attempts small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.sd-attempts strong{font-size:9px}.sd-attempts small{color:#8F765B;font-size:7.5px}.sd-attempts b{color:#6B1E2D;font-size:10px}.sd-muted{margin:0;color:#8F765B;font-size:9px;font-weight:700}.sd-assign{grid-column:1/-1;display:flex;align-items:center;gap:10px}.sd-assign>span{color:#655B53;font-size:10px;font-weight:900}.sd-assign select{flex:1;height:38px;padding:0 10px;border:1px solid rgba(184,160,130,.28);border-radius:11px;background:#FFFBF5;color:#32101A;font:700 10px 'Cairo',sans-serif;outline:0}.sd-empty{min-height:260px;display:grid;place-items:center;align-content:center;gap:10px;border:1px dashed rgba(107,30,45,.22);border-radius:22px;background:#FFFBF5;color:#8F765B;text-align:center}.sd-empty p{margin:0;font-size:12px;font-weight:800}.sd-empty button{padding:8px 18px;border:0;border-radius:10px;background:#6B1E2D;color:#FFF;font:800 10px 'Cairo',sans-serif;cursor:pointer}
@media(max-width:1120px){.sd-hero{grid-template-columns:1fr}.sd-hero-metrics{grid-template-columns:repeat(4,1fr)}.sd-grid{grid-template-columns:1fr}}@media(max-width:720px){.sd-hero{padding:21px;border-radius:21px}.sd-hero h1{font-size:24px}.sd-hero-metrics{grid-template-columns:repeat(2,1fr)}.sd-toolbar>label{min-width:100%}.sd-toolbar button,.sd-toolbar a{flex:1}.sd-filters>div{grid-template-columns:1fr}.sd-card{padding:14px;border-radius:20px}.sd-expanded{grid-template-columns:1fr}}@media(max-width:480px){.sd-contact span:first-child{max-width:210px}.sd-card-summary{grid-template-columns:1fr}.sd-ring{position:absolute;inset-inline-end:10px;top:8px;width:50px;height:50px}.sd-position{padding-inline-end:55px}.sd-card-actions{grid-template-columns:1fr}.sd-card-metrics{gap:4px}.sd-name-row h2{font-size:14px}}@media(prefers-reduced-motion:reduce){.sd-card,.sd-expanded,.sd-hero-art{animation:none!important;transition:none!important}}
`;
